<?php

declare(strict_types=1);

namespace App\Tests\Controller\Catalog;

use App\Data\ArticleFilterData;
use App\Repository\AlbumRepository;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\DomCrawler\Crawler;

class ProductionControllerTest extends WebTestCase
{
    private ?KernelBrowser $client = null;
    private ?Crawler $crawler = null;
    private const PRODUCTION_URI = '/production';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = self::createClient();
        $this->crawler = $this->client->request('GET', self::PRODUCTION_URI);
    }

    public function testAccessProductionPage(): void
    {
        $this->client->request('GET', self::PRODUCTION_URI);
        self::assertResponseIsSuccessful();
    }

    public function testCheckboxProduction(): void
    {
        $checkbox = $this->crawler->filter('input[name="globalFilters[kbrProduction]"]');
        $isOwnProduction = $checkbox->attr('checked');

        self::assertTrue((bool) $isOwnProduction, 'la checkbox doit être checké');
    }

    public function testDisplayCorrectNumberProduction(): void
    {
        $badge = $this->crawler->filter('[data-test-badge="count-production"]')->first()->text();

        $filters = new ArticleFilterData();
        $filters->kbrProduction = true;

        // Counted in albums, not pressings: the grid shows one card per record.
        $albumRepository = self::getContainer()->get(AlbumRepository::class);
        $ownProdAlbums = $albumRepository->filterAlbumQuery($filters);
        $numberProdAlbums = count($ownProdAlbums->getResult());

        self::assertEquals((string) $numberProdAlbums.' éléments trouvés.', $badge);
    }
}
