vich_uploader:
    db_driver: orm

    mappings:
        albums:
            uri_prefix: /albums
            upload_destination: '%kernel.project_dir%/public/upload/albums'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
