<?php

declare(strict_types=1);

namespace App\Tests\Controller\Admin;

use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;

/**
 * Renders every EasyAdmin CRUD index and its "new" form.
 *
 * EasyAdmin resolves fields at render time — a field type that does not match its property
 * (a TextField on an enum, a form asking for a Gedmo-generated slug) only blows up when
 * the page is actually rendered, never during static analysis.
 */
class AdminSmokeTest extends WebTestCase
{
    private ?KernelBrowser $client = null;

    /**
     * Route name prefixes generated by EasyAdmin, derived from each CRUD controller name.
     */
    private const array CRUD_ROUTES = [
        'admin_album',
        'admin_article',
        'admin_artist',
        'admin_edition',
        'admin_image',
        'admin_label',
        'admin_order',
        'admin_payment',
        'admin_social_network',
        'admin_song',
        'admin_style',
        'admin_support',
        'admin_transporter',
    ];

    protected function setUp(): void
    {
        parent::setUp();
        $this->client = self::createClient();

        $admin = self::getContainer()->get(UserRepository::class)->findOneBy(['email' => 'maxiloud@gmail.com']);
        self::assertNotNull($admin, 'la fixture user_admin est absente de la base de test');

        $this->client->loginUser($admin);
    }

    public function testDashboardIsReachable(): void
    {
        $this->client->request('GET', '/admin');
        self::assertResponseRedirects();
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function crudRouteProvider(): iterable
    {
        foreach (self::CRUD_ROUTES as $route) {
            yield $route => [$route];
        }
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('crudRouteProvider')]
    public function testCrudIndexRenders(string $routeName): void
    {
        $url = self::getContainer()->get('router')->generate($routeName.'_index');

        $this->client->request('GET', $url);

        self::assertResponseIsSuccessful(sprintf('la liste %s ne s\'affiche pas', $routeName));
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('crudRouteProvider')]
    public function testCrudNewFormRenders(string $routeName): void
    {
        $url = self::getContainer()->get('router')->generate($routeName.'_new');

        $this->client->request('GET', $url);

        // Order and Payment are created by the checkout flow, not by hand: EasyAdmin
        // answers 403 when the NEW action is disabled, which is a valid outcome here.
        self::assertContains(
            $this->client->getResponse()->getStatusCode(),
            [Response::HTTP_OK, Response::HTTP_FORBIDDEN],
            sprintf('le formulaire de création %s ne s\'affiche pas', $routeName)
        );
    }
}
